spring.application.name=zeniel_ai

# PostgreSQL 설정
spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.username= ${USERNAME}
spring.datasource.password= ${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# openAI 설정
spring.ai.openai.api-key= ${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small

# PGVector 설정
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

# 트랜잭션 로그 확인 (디버깅용)
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

# Elasticsearch 설정
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=your_password